display_name: 哨兵加速器
package_name: sentinelvpn
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - SentinelVPN
  - Clash
  - ClashMeta
  - Proxy

generic_name: 哨兵加速器

categories:
  - Network

startup_notify: true